### ISSUE TITLE
cannot find module 'ng-diff-match-patch'

### ISSUE THREAD

**Issue by chauey** [elliotforbes/ng-diff-match-patch#11]
I get this error even though it is installed, imported, and added to import array. Any ideas? Thanks.

**Comment by rars** [comment]
Which version of `ng-diff-match-patch` are you using? Can you provide some code snippets to show what you're doing please?

**Comment by chauey** [comment]
it was the latest version i believe. someone else was testing and now they have removed the code so we do not need to fix this any more at the moment. thanks.

**Comment by glynthink** [comment]
I am having the same issue, the issue appeared when I updated to the latest angular material (2.0.0-beta.8)

**Comment by rars** [comment]
Which version of Ng-diff-match-patch do you have installed?

**Comment by glynthink** [comment]
Latest one (1.1.0)

**Comment by rars** [comment]
Try downgrading to 1.0.3. The 1.1.0 package is missing the index.ts file. I've raised this with @elliotforbes.

**Comment by glynthink** [comment]
Yes thanks, downgrading to 1.0.3 seems to have solved it.

**Comment by elliotforbes** [comment]
I believe this issue is now solved in 1.2.2 of the package. Please let me know if this works for you @rars

**Comment by rars** [comment]
Thanks @elliotforbes. I've got a test project that I've tested against locally. When I build with 1.2.2 I get a `ERROR in DiffMatchPatchModule is not an NgModule` message. The 1.2.2 package seems to be missing the `.metadata.json` files from the `dist` folder. When I add those in the error goes away and it compiles successfully. This is from an `import { DiffMatchPatchModule } from 'ng-diff-match-patch';` statement.

**Comment by jmls** [comment]
yup - just hit the exact problem above

**Comment by rars** [comment]
I downloaded the 2.0.0 package and it didn't contain the dust folder. Can you check and republish please?

**Comment by rars** [comment]
The 2.0.1 package doesn't contain all the files that should be generated. Specifically, it only contains the `.bundle.js`. The other files are important for e.g. `.d.ts` files for Typescript projects, `.metadata.js` for AoT compilation, `.module.js` for bundlers that understand esm.

Have you come across this article:
http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/
It's a good overview of the different files that should be produced in the dist folder and the reasons for why they are included. It's what I followed in my previous PR https://github.com/elliotforbes/ng-diff-match-patch/pull/8

Can you take another look when you get chance please?

**Comment by elliotforbes** [comment]
issue solved, the files array was set in the package.json which was excluding the publishing of all the files in the dist folder. I've taken that out and it looks good now, can you verify?

**Comment by rars** [comment]
Yeah, looks good now. Thanks!

**Comment by elliotforbes** [comment]
awesome, I appreciate the help and guidance! I'll close this issue!
